

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db-1

    ports:
      - 5432:5432

  # volumes:
  #   postgres-data:
